# Generated by Django 4.2.7 on 2023-11-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_options_alter_news_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_image',
            new_name='category_image',
        ),
        migrations.AddField(
            model_name='news',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
